server:  port: 9090  spring:  application:    name: api-gateway-zuul  profiles:     include:    - dev, uat, prod    active:    - dev, uat    #Eureka Configeureka:  instance:    hostname: localhost  client:    register-with-eureka: true    fetch-registry: true    service-url:      defaultZone: http://localhost:8761/eureka#ZUUL Config
zuul:  host:    socket-timeout-millis: 50000
  routes:    sleuth-client:
      path: /client/**
      service-id: sleuth-client
    sleuth-server:
      path: /server/**
      service-id: sleuth-server      #Actuator Configmanagement:  endpoints:    web:      exposure:        include:        - "*" #this will add all actuator endpoints  endpoint:    health:      show-details: always